# for module compiling
import os
from building import *

cwd = GetCurrentDir()
objs = []

list = os.listdir(GetCurrentDir())
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

cwd = cwd + '\..'
objs = objs + SConscript(os.path.join(cwd, 'SConscript'))

Return('objs')
