from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd, cwd + "/utilities"]
objs = []

group = DefineGroup('MCIMX6Y2', src, depend = [''], CPPPATH = CPPPATH)

SrcRemove(src, ['system_MCIMX6Y2.c'])

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
