from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

if not GetDepend('RT_USING_SERIAL'):
    SrcRemove(src, ['drv_uart.c'])

if not GetDepend('RT_USING_SPI'):
    SrcRemove(src, ['drv_spi.c'])

if not GetDepend('RT_USING_I2C'):
    SrcRemove(src, ['drv_i2c.c'])

if not GetDepend('RT_USING_RGBLCD'):
    SrcRemove(src, ['drv_lcd.c'])

if not GetDepend('BSP_USING_SDHC'):
    SrcRemove(src, ['drv_sdhc.c'])

group = DefineGroup('Driver', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
