from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

if not GetDepend('RT_USING_GT7147'):
    SrcRemove(src, ['drv_gt9147.c'])

if not GetDepend('RT_USING_ICM20608'):
    SrcRemove(src, ['drv_icm20608.c'])

if not GetDepend('RT_USING_PCF8574'):
    SrcRemove(src, ['drv_pcf8574x.c'])

if not GetDepend('RT_USING_LAN8720'):
    SrcRemove(src, ['drv_lan8720.c'])

if not GetDepend('RT_USING_SDCARD'):
    SrcRemove(src, ['drv_sd.c'])

group = DefineGroup('Device', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
