from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

if GetDepend('BSP_USING_LVGL_GPU'):
    group = DefineGroup('lv_gpu', src, depend = [''], CPPPATH = CPPPATH)

    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
    objs = objs + group

Return('objs')
